### ISSUE TITLE
Artemis Thing Plus - why are buttons commented out?

### ISSUE THREAD

**Issue by MrOneTwo** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#18]
https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/blob/df63d05632d6146bdf536628d4bf5ffcaa99e553/artemis_thing_plus/bsp/am_bsp.h#L107

It seems Artemis Thing Plus has a button that connects to the pin `D10`. Why is it commented out?

**Comment by oclyke** [comment]
Must've overlooked it! Thanks for the heads up. 

The button on Artemis Thing Plus should now be accessible on the pin called
```AM_BSP_GPIO_BUTTON0``` (also aliased to ```AM_BSP_GPIO_BUTTON10``` and ```AM_BSP_GPIO_SWCH```)

and as an Ambiq Devices 'Button' 

``` c
am_devices_button_t am_bsp_psButtons[AM_BSP_NUM_BUTTONS] =
{
    AM_DEVICES_BUTTON(AM_BSP_GPIO_BUTTON0, AM_DEVICES_BUTTON_NORMAL_HIGH)
};
```

```#define AM_BSP_NUM_BUTTONS                  1```
