### ISSUE TITLE
BSPs don't expose SWO pin for ITM

### ISSUE THREAD

**Issue by justiceamoh** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#19]
The BSP files for the Sparkfun boards don't declare the ITM SWO pin. Typically, this should be in both [am_bsp_pins.h](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/blob/4f4680b90d27e0fc08d7aed38dc8bfe38ab4730b/redboard_artemis_nano/bsp/am_bsp_pins.h#L554) and [am_bsp_pins.c](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/blob/4f4680b90d27e0fc08d7aed38dc8bfe38ab4730b/redboard_artemis_nano/bsp/am_bsp_pins.c#L833).  

In the BSP file for the apollo3 eval boards, its provided in `am_bsp_pins.h` as:
```c
//*****************************************************************************
//
//  ITM_SWO pin: ITM Serial Wire Output.
//
//*****************************************************************************
#define AM_BSP_GPIO_ITM_SWO             41
extern const am_hal_gpio_pincfg_t       g_AM_BSP_GPIO_ITM_SWO;
```

And in the corresponding `am_bsp_pins.h` as:
```c
//*****************************************************************************
//
//  ITM_SWO pin: ITM Serial Wire Output.
//
//*****************************************************************************
const am_hal_gpio_pincfg_t g_AM_BSP_GPIO_ITM_SWO =
{
    .uFuncSel            = AM_HAL_PIN_41_SWO,
    .eDriveStrength      = AM_HAL_GPIO_PIN_DRIVESTRENGTH_2MA
};
```

**Comment by oclyke** [comment]
@justiceamoh Thanks!

On Most of the Artemis boards a dedicated SWO pin is not exposed so (to me at least) it doesn't make sense to provide a BSP name for one. (Yes, I think it is an oversight to not include this pin when possible so I will open issues on the corresponding HW)

Here's the relevant part of the schematic for Artemis boards:
![artemis](https://user-images.githubusercontent.com/13486034/70174432-24673000-1692-11ea-928c-a0806f194277.JPG)

But on the Edge board there is a dedicated SWO pin on the SWD connector:
![edge](https://user-images.githubusercontent.com/13486034/70174452-30eb8880-1692-11ea-84f9-2844c403d5da.JPG)

If you want to use SWO on Artemis the best way is to declare your own SWO pin. The pins that have the capability and are exposed on the Artemis module are:

| Pad # |
| --- |
| 15 |
| 22 |
| 24 |
| 33 |
| 41 |
| 45 |
| 46 |

But of course only some of those may be available on the given breakout board (RedBoard, ATP, Nano, Thing plus, Edge2)


You could use something like this to make sure that ```AM_BSP_GPIO_ITM_SWO``` and ```g_AM_BSP_GPIO_ITM_SWO``` are available in your application with your pin number ```MYPINNUM``` w/ the convenience that an invalid pin number will not be caught b/c the corresponding HAL macro does not exist.

(You may need to modify the bsp files to expect this)
``` c
#define _DECLARE_ITM_PIN(P) const am_hal_gpio_pincfg_t g_AM_BSP_GPIO_ITM_SWO = { \
                                                                                .uFuncSel = AM_HAL_PIN_ ## P ## _SWO, \
                                                                                .eDriveStrength = AM_HAL_GPIO_PIN_DRIVESTRENGTH_2MA, \
                                                                              }
#define DECLARE_ITM_PIN(N) _DECLARE_ITM_PIN(N)

#define MYPINNUM 33
#define AM_BSP_GPIO_ITM_SWO MYPINNUM
DECLARE_ITM_PIN(AM_BSP_GPIO_ITM_SWO);
```

**Comment by oclyke** [comment]
I added the exposed ITM pin for the Edge board and updated the bsp library

**Comment by justiceamoh** [comment]
Oh I see! Thanks for your response @oclyke, very helpful.  I assumed SWO was actually exposed in the debug interface but you're right that its not. That's probably why I've had no luck in my attempts to use ITM/SWO. I definitely vote for including the pin in the HW: it will enable full debug features (eg. SWV data trace) for the Artemis boards. 

Thank you very much for the suggestion of declaring my own SWO. I'll give that a shot.

**Comment by oclyke** [comment]
My pleasure! I appreciate your involvement

**Comment by MrOneTwo** [comment]
@oclyke 

I've tried to implement pin 33 for the Artemis Thing Plus (it seems that's the pin that's routed to the SWD header) and still no luck... I've defined the pin in pins files and removed comments in the `am_bsp.c`. Any pointers? I'm attaching a patch file. I hope you don't mind me posting it here, and if you do, please tell me :)

[boards_sfe_SWO33.zip](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/files/3936500/boards_sfe_SWO33.zip)

**Comment by oclyke** [comment]
I don't mind but you should be recognized for contributing to the repository. Using Git makes that pretty easy.

I'll walk you through how to make a pull request. 
* Make sure you have GitHub Desktop installed 
* Go to the BSP repo and click 'Fork' near the top. This will create a copy of the repo that you have permission to edit. 
* Go to your fork and click 'Clone or Download' then 'Open in Desktop' (you may need to make sure you are logged in on GitHub for it to link with your desktop application.
* In GitHub Desktop choose where to put the repository then click 'clone' - it will download the fork.
* Click on the button that says 'Current Branch' and 'master' then click on the 'New Branch' button. Type in the name of the branch you wan to create (a branch is a development area for a specific feature so you might calls yours 'expose-artemis-thing-plus-swo')
* The branch button should now say that you are on your new branch
* Then on your computer make the changes you want to the necessary files.
* As you save changes to your computer GitHub Desktop will show you a list of all the changes you've made. You can choose which (or all) of the changes to commit with a given message. If you have many changes then it can help to break it up into several commits that each represent a single theme.
* Once you've made all the changes you want and committed them click on the 'Push origin' button. That will sync up your local changes to your GitHub fork. 
* Finally you will be able to make a pull request of your changes into this repo. Visit your fork's repository page on GitHub and click 'Open a Pull Request.' Make sure that you are comparing this repo's master branch with the branch you made in your fork. Finalize that and we will be able to have a discussion about the changes (if needed) and then I will accept the PR - then you will be a contributor (officially!) 

Apologies if you already know all this...

**Comment by MrOneTwo** [comment]
@oclyke Oh, yes I know this. I don't want to merge those changes though since as you pointed out in this https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/issues/19#issuecomment-561815223 comment there is no dedicated pin for SWO. I just tried to setup the pin 33 as a SWO in my own setup and I still can't get the SWO to work.

I was hoping that maybe you or someone who is interested in making it work could help me by looking at the changes I've introduced in the patch.

**Comment by oclyke** [comment]
Actually I think I mis-spoke about the Artemis Thing Plus. It does appear to have the SWO pin connected on the debug header. (https://github.com/sparkfun/Artemis_Thing_Plus/issues/1)

I'm taking a look at your changes now - didn't realize it was a ```.patch```, that is much more helpful (thought it was a zip of the whole repo including your changes)

Alright your changes look correct to me but that's not necessarily saying much because I have rarely (if ever?) used ITM/SWO. That's because our typical customer will not have a debugger on hand (however that might be changing with the inexpensive segger edu devices)

What code are you using? Have you tried an example from the Apollo3 Eval Board? I know that Ambiq makes pretty extensive use of ITM in their examples - just always replaced _itm_ with _uart_ and forgot about it.

@justiceamoh Checking out MrOneTwo's patch file made me realize that the BSPs had commented out the ITM pin configuration within the ```am_bsp_itm_printf_enable``` function. I've just corrected this with preprocessor gates. Maybe that had something to do with your issue?

**Comment by MrOneTwo** [comment]
I've tried a simple blinky example, which by default inits the ITM, and tried to send a message. No luck.

I'm really a bit confused why it's not working. Also the pin configuration line in the `am_bsp_itm_printf_enable` is there twice... which is annoying as hell. I'm not sure it's needed. I'll try to investigate. It just looks so sloppy...

Well if you @oclyke are ok with that I think everyone would appreciate having the pin definitions for SWO by default. I'm pretty new to ITM myself but I find it pretty cool. It's like a next step for someone who is a bit tired of the UART debugging. I'm personally using the *Segger Edu Mini* and it's a quality product. I hope your customers will embrace that ;)

**Comment by MrOneTwo** [comment]
Ok I've looked at the `am_bsp.c` in the `AmbiqSuiteSDK/boards/apollo3_evb/bsp/` and there the first `am_hal_gpio_pinconfig(AM_BSP_GPIO_ITM_SWO, g_AM_BSP_GPIO_ITM_SWO);` is commented out and the second one isn't.

What I think is the best way to go is to first figure out the ITM so it works, and deleting the redundant `am_hal_gpio_pinconfig` in the *SparkFun*'s `am_bsp.c`.

**Comment by oclyke** [comment]
I agree. I will re-open this issue so that we can get it taken care of properly once and for all.

**Comment by oclyke** [comment]
Another thought - right now BSPs are included as precompiled archives. (It is how it was done for the Ambiq boards so we followed suit) This will cause trouble for people who want to define their own ITM pins and call the BSP itm setup functions. There are three cases:
1. BSP has ITM pin definition, user wants to use as-is
	- this case should work right now
1. BSP has ITM pin definition, user wants to use define their own
	- the ```am_bsp_itm_printf_enable``` function was compiled to create the ```lib_am_bsp.a``` archive. At that time the BSPs ```AM_BSP_GPIO_ITM_SWO``` macro was used in text replacement by the preprocessor in the function. It is now impossible to call ```am_bsp_itm_printf_enable``` and have it configure the custom ITM pin.
1. BSP has no ITM pin definition, user wants to define their own
	- similarly to the case above the preprocessor has removed the pin configuration call from ```am_bsp_itm_printf_enable``` because ```AM_BSP_GPIO_ITM_SWO``` was not defined at the time

Preferably the BSPs will only represent hardware/functionality that is 'supported' by the board. So I am mildly opposed to presenting a definition for ```AM_BSP_GPIO_ITM_SWO``` where it is not extremely clear where to access the ITM/SWO. 

However I definitely think people should be able to hook into ITM/SWO easily (not have to go through the same level of trouble you have - sorry!)

Solutions:
* Don't precompile the library.
	- Users could then add their own pin definitions to the BSP manually. To preserve the integrity of the pin definitions I would suggest adding a compilation unit (e.g. custom_pins.c and custom_pins.h) and including the header file in "am_bsp.h"
	``` c
	#ifndef AM_BSP_H
	#define AM_BSP_H
	
	#include <stdint.h>
	#include <stdbool.h>
	#include "am_mcu_apollo.h"
	#include "am_bsp_pins.h"
	#include "custom_pins.h"
	
	...
	
	#endif // AM_BSP_H
	```
	- Add the BSP source files to the build.
	- This method requires the user to modify the BSP which could be messy and or hard to maintain/debug. 
* Force users to implement their own ```am_bsp_itm_printf_enable``` when it is not supported by the board.
	- the entire ```am_bsp_itm_printf_enable``` function would get the preprocessor gate so that trying to use it in an unsupported board would error out. In fact, if the default pin is not defined then an alternate function signature could be provided - one that allows the user to pass in the pin number and configuration structure. I like that idea so I will make a branch for you to try out.

**Comment by MrOneTwo** [comment]
@oclyke Well you certainly describe the situation well... I can't say what would be best. I like the "symmetry" of the BSPs you supply and the ones in the Ambiq SDK (`boards/apollo3_evb` for example). Introducing changes in the structure/files of `boards_sfe` poses a lot of problems.

I have spent several days figuring out what's going on in the SDK and your BSP. Personally this parity/symmetry is important. Introducing *gotchas* makes the user experience worse. I'm obviously not saying that any changes are bad. I'm just trying to communicate what reduces the friction for me. Documenting things like that is very important and can reduce the friction significantly too.

In the end my goal is to make the HID app working and there is A LOT of guess work and trail and error. I do recognize that those apps aren't SparkFun's code so I don't expect SparkFun to document and improve that code. I expect myself to do it ;) (I'm describing my development process [here](http://ciesie.com/post/fa92eb_sparkfunthingplus01/)). This guess work makes it very hard to recommend Artemis boards, even though the boards themselves are great. What I'm trying to say is that the hardware is only as good as its software - sorry for the rant ;)

I think the SparkFun's BSP should provide a default SWO pin definition, for the pin that is routed to the header. If the user wants to move the SWO to a different pin they should implement their own `am_bsp_itm_printf_enable`, just as you suggested.

Most of the users won't need the ITM. The ones that will need the ITM will expect it to work by just calling the default functions like `am_bsp_itm_printf_enable` (I'm in this camp). Those people will quickly take a look at the schematic, see the SWO pin on the header and be like *Cool! Should work.*. Then there is a very small group of people who will not only need the ITM but will also need to move it to a different pin.

Again, sorry for the long post. I'm up for testing any branch you'll prepare. I'm here for you ❤️

**Comment by oclyke** [comment]
@MrOneTwo I agree that it should work out of the box on boards where the SWO pin is routed to the JTAG header. In the branch [```itm-alternatives```](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/tree/itm-alternatives) I have made the proposed changes as well as added the pin definition for the Artemis Thing Plus. 

Would you and @justiceamoh be willing to test-drive the code from PR [#21](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/pull/21)?

**Comment by oclyke** [comment]
Gah! I'm so unobservant.... Somehow I missed the fact that all of the board in fact DO have ITM_SWO pins exposed on the debug headers. What a mess. @justiceamoh, @MrOneTwo my apologies. All the boards should work with any ITM example by default now. SWO baud rate still defaults to 2M

**Comment by MrOneTwo** [comment]
Since the branch have been merged it's probably better to respond here. 

I've tested the changes with setting the SWO baud rate with `-swofreq 2000000` and it works as expected :) I guess it's important to set it explicitly.

Thank you for your help. I think we can consider this one solved once and for all.
