### ISSUE TITLE
The `am_bsp_low_power_init` looks suspicious

### ISSUE THREAD

**Issue by MrOneTwo** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#24]
https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/blob/f7745949f21040f644927a9ccddbf576f6f64a02/artemis_thing_plus/bsp/am_bsp.c#L202

Why call `am_hal_rtc_osc_disable` twice? Does it *init* the low power functionality or actually sets it? Initing seems more like initing structures etc. I might be missing something but I'm trying to get the whole Cordio app to work (which is a nightmare), and I'm trying to understand the sleep modes. The API doesn't help.

Are we in a situation in which some low power functionality has to be inited but it doesn't impact the state of the MCU, and then later we toggle the sleep state? Or is it just a situation in which we flip sleep mode On/Off without a need to prepare the initial state?

The API suggests the first one is true but is it really...?

I hope you can understand my confusion. I know I don't explain it particularly well.

**Comment by oclyke** [comment]
I think I understand why you are confused, but I can't offer any worthy explanation other than "that's what Ambiq decided to call this function in their examples and to be compatible we have to keep the name the same." 

I *think* it is like the second case but with a difference. The difference being that there is no 'high_power_init' function. So it is like an OFF switch by itself. You can choose to deinitialize and un-set-up everything (going into lowest power state) and then actions that you do after that will accumulate and put the chip into a higher power state as needed. E.g. needing to clock the SPI peripheral at high speed probably automatically enables the HFRC or XTAL clocks which use more power.

**Comment by MrOneTwo** [comment]
@oclyke Ok, thank you. I need to spend more time trying to understand the low power mode fully. Thank you for fixing the code.
