### ISSUE TITLE
Having trouble with adding button pins

### ISSUE THREAD

**Issue by MrOneTwo** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#30]
I've added a few button pins to the bsp and it doesn't seem to work... Can't really figure it out. I wanted to ask if I'm missing something. I'm attaching a diff file. I'm using the release before updating the Ambiq SDK to 2.3.2.

[buttons.diff.txt](https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/files/4475856/buttons.diff.txt)

It works ok with the built-in button.

**Comment by oclyke** [comment]
Are you using this in the context of the SDK? If so then the BSPs are linked in as a static library - the sources are not compiled every time. So you will need to re-compile your BSP changes. This can be done using the makefile in the BSP directory. There is also a script that can accomplish what you need. ```common/tools_sfe/scripts/regen_bsps.sh```

**Comment by MrOneTwo** [comment]
I do use SDK and I do indeed rebuild those libs.

**Comment by oclyke** [comment]
Alright, In that case what are the symptoms? What do you mean when you say it does not work?

**Comment by MrOneTwo** [comment]
I'm running a HID BLE code. I have a button handler function which runs on a timer. It detects presses on the default, built-in button. I have two other buttons soldered with a 4k7 pull up resistor (and I've the default 1k5 pullup resistor via the Apollo's pullups). Those aren't being detected and they should be handled the same way the default buttons is. I've found several places where I had to make change (i.e. the number of buttons), so I thought I might have missed something.

**Comment by oclyke** [comment]
Hmm. I'm not familiar with your particular code so I don't really know if you are missing anything. All I can recommend is to try a simplified test case for the buttons. I just looked in the Apollo3 examples in the SDK and did not find any button examples so you may want to write your own.

If your simplified test code reveals some issues feel free to re-open and share the test - then I can look into it further.

**Comment by MrOneTwo** [comment]
Ok, thank you!

**Comment by MrOneTwo** [comment]
Ok I have figured it out ... I think.

I have mixed the `devices` API with `HAL` API. I've called the `am_devices_button_array_init` which disables the pins. Calling other functions from `am_devices` family turns those pins on when reading but not before.

I'm a bit confused a bit about one thing. When we describe button pins we for example specify pull up resistor value. Later, when we turn the pin on (`am_devices_button_tick` line 133) we use the `g_AM_HAL_GPIO_INPUT`. Why don't we use `g_AM_HAL_GPIO_INPUT_PULLUP_1_5`? Or `..._PULLUP_6` if I describe the pin using 6k pullup. `am_devices_button_tick` always uses the generic `g_AM_HAL_GPIO_INPUT`.

edit: I also made it work in the WSF/BLE setup.
